### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by rbarlow** [kivra/oauth2#61]
Hello!

I am working on packaging oauth2 for Fedora Rawhide, and the latest release (0.6.0) won't build due to https://github.com/kivra/oauth2/issues/59. Would you be willing to make a release with that fix so we can build there? Thanks so much for your consideration!

**Comment by bipthelin** [comment]
Done.

**Comment by rbarlow** [comment]
Thanks a lot @bipthelin!

This package has been accepted into Fedora:

https://admin.fedoraproject.org/pkgdb/package/rpms/erlang-oauth2/
