### ISSUE TITLE
4.2.1.  Authorization Request - client_secret is required?

### ISSUE THREAD

**Issue by hachreak** [kivra/oauth2#62]
I have a question:
On a `Authorization Request - Implicit Grant`, the client authentication with `client_id`/`client_secret` is required?
https://github.com/kivra/oauth2/blob/master/src/oauth2.erl#L120
Because in the RFC they didn't mention the `client_secret`.
Maybe is enough check if the client exists.

**Comment by mdaguete** [comment]
@hachreak you're ok .. the RFC mentions:

> The implicit grant type does not include client authentication, and
   relies on the presence of the resource owner and the registration of
   the redirection URI.

with the provided function a secret is needed to perform auth. 

In https://github.com/kivra/oauth2_example/blob/master/src/oauth2_example_auth.erl#L153 you can see an alternative implementation

**Comment by bipthelin** [comment]
This is fixed with https://github.com/kivra/oauth2/pull/64
